#!/bin/bash
#==============================================================================
#TITLE:            analyser
#DESCRIPTION:      This tool analyses various system logs for key information
#AUTHOR:           Louis Ouellet
#DATE:             2022-03-04
#VERSION:          22.03-04

#==============================================================================
# INIT
#==============================================================================

# Pull Basher
if [[ ! -f "${scriptDirectory}vendor/basher/basher" ]]; then
  git submodule update
fi

# Source Basher
source ${scriptDirectory}vendor/basher/basher

#==============================================================================
# SCRIPT PERSONALISATION
#==============================================================================

# Script Personalisation
helpOptions="${helpOptions}"

#==============================================================================
# FUNCTIONS
#==============================================================================

function vmail_maxUser(){
  log="/var/log/syslog"
  accounts="/tmp/accounts.list"
  vmail_maxUser="/tmp/vmail.pid"
  if [[ -f "${accounts}" ]]; then rm ${accounts}; fi
  if [[ -f "${vmail_maxUser}" ]]; then
    if ps -p $(cat ${vmail_maxUser}) > /dev/null; then kill $(cat ${vmail_maxUser}); fi
    rm ${vmail_maxUser}
  fi
  if [[ -f "${log}" ]]; then
    while true; do
      for account in $(cat ${log} | grep 'Inotify instance limit for user' | grep 'Increase /proc/sys/fs/inotify/max_user_instances' | cut -d\( -f2 | cut -d\) -f1); do
        touch ${accounts}
        if [[ ${account} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ "$(cat ${accounts} 2> /dev/null | grep ${account})" == "" ]]; then
          echo ${account} | tee -a ${accounts} | dbg i c
        fi
      done
    done &
    if [[ ! -f "${vmail_maxUser}" ]]; then touch ${vmail_maxUser}; fi
    echo $! > ${vmail_maxUser}
    while read -sn 1 key && [[ ${key} != 'q' ]]; do
      echo "Key ${key}" > /dev/null
    done
    kill %1
    if [[ "${debugSend}" != "true" ]]; then
      echo "Do you want to send an email?(n)[y/n]"
      read email
    fi
    if [[ "${email}" == "y" ]] || [[ "${email}" == "Y" ]] || [[ "${debugSend}" == "true" ]]; then
      send -a ${ips} "Analyser Report - vmail_maxUser" "See attached Bruteforce Report."
    fi
  else
    error "${log} file does not exist!"
  fi
}

function sasl(){
  log="/var/log/syslog"
  ips="/tmp/ips.list"
  passwords="/tmp/passwords.list"
  sasl="/tmp/sasl.pid"
  if [[ -f "${ips}" ]]; then rm ${ips}; fi
  if [[ -f "${sasl}" ]]; then
    if ps -p $(cat ${sasl}) > /dev/null; then kill $(cat ${sasl}); fi
    rm ${sasl}
  fi
  if [[ -f "${log}" ]]; then
    echo "Do you want to block the IPs?(n)[y/n]"
    read block
    while true; do
      for ip in $(cat ${log} | grep 'SASL LOGIN authentication failed' | cut -d[ -f3 | cut -d] -f1); do
        touch ${ips}
        if [[ ${ip} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ "$(cat ${ips} 2> /dev/null | grep ${ip})" == "" ]]; then
          echo ${ip} | tee -a ${ips} | dbg i c
          if [[ "${block}" == "y" ]] || [[ "${block}" == "Y" ]]; then
            if [[ "$(ip route show ${ip} | wc -l)" -eq 0 ]]; then
              if [[ "${ip}" != "127.0.0.1" ]]; then
                exec "route add -host ${ip} reject"
              fi
            fi
          fi
        fi
      done
      for password in $(cat ${log} | grep 'SASL LOGIN authentication failed' | egrep -v 'Connection lost to authentication server' | cut -d: -f7); do
        password=$(echo ${password} | xargs | base64 -d)
        if [[ "$(cat ${passwords} 2> /dev/null | grep ${password})" == "" ]]; then
          echo ${password} | tee -a ${passwords} | dbg i c
        fi
      done
    done &
    if [[ ! -f "${sasl}" ]]; then touch ${sasl}; fi
    echo $! > ${sasl}
    while read -sn 1 key && [[ ${key} != 'q' ]]; do
      echo "Key ${key}" > /dev/null
    done
    kill %1
    if [[ "${debugSend}" != "true" ]]; then
      echo "Do you want to send an email?(n)[y/n]"
      read email
    fi
    if [[ "${email}" == "y" ]] || [[ "${email}" == "Y" ]] || [[ "${debugSend}" == "true" ]]; then
      send -a ${ips} -a ${passwords} "Analyser Report - sasl" "See attached Bruteforce Report."
    fi
  else
    error "${log} file does not exist!"
  fi
}

#==============================================================================
# RUN OPTIONS & FUNCTIONS
#==============================================================================

parameters=
while getopts "${opts}p:" option; do
	case "${option}" in
    p)
      parameters="${parameters} ${OPTARG}"
      ;;
    -)
      case "${OPTARG}" in
        *=*)
          val=${OPTARG#*=}
          opt=${OPTARG%=$val}
          lookup "-${opt}" ${val}
          ;;
        *)
          val="${!OPTIND}"
          OPTIND=$((OPTIND +1))
          lookup "-${OPTARG}" ${val}
          ;;
      esac
      ;;
    *)
      lookup "${option}" ${OPTARG}
      ;;
	esac
done
shift $((OPTIND -1))

#==============================================================================
# RUN SCRIPT
#==============================================================================

if [[ "$1" != "" ]]; then
  function=$1
  if [[ $(type -t ${function}) == function ]]; then
    eval ${function} ${@:2}
  else
    echo
    echo "Invalid function: ${function} ${@:2}"
    echo
    help
    exit 0
  fi
else
  echo
  echo "Invalid function: ${function} ${@:2}"
  echo
  help
  exit 0
fi

if [[ "${verboseMode}" == "true" ]]; then
  duration=$SECONDS
  echo "#############################################################" | dbg i e
  echo "log file.......: ${logFile}" | dbg i v
  echo "$((${duration} / 60)) minutes and $((${duration} % 60)) seconds elapsed." | dbg i v
  echo "#############################################################" | dbg i e
  if [[ "${debugMode}" == "true" ]] && [[ "${debugSend}" == "true" ]]; then
    send -a ${logFile} "Debug Report" "See attached report."
  fi
fi

if [[ "${debugMode}" == "true" ]] && [[ "${debugError}" == "true" ]]; then
  if [[ -f "${logFile}" ]]; then
    case "${OS}" in
      Mac)cat ${logFile} | egrep '(✗|!)';;
      *)cat ${logFile} | egrep '✗|!';;
    esac;
  fi
fi

exit 0
